trainer:
  max_epochs: 3
  log_every_n_steps: 1
  accelerator: "mps"
  default_root_dir: ~/training_logs
  devices:
    - 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        save_last: FALSE
        filename: "{epoch}-{val_loss:.2f}"

model:
  class_path: ftw_ma.trainers.CustomSemanticSegmentationTask
  # class_path: trainers.CustomSemanticSegmentationTask
  init_args:
    loss: localtversky #"ce", "focal", "dice", "localtversky"
    model: unet
    backbone: efficientnet-b3
    weights: TRUE
    patch_weights : FALSE
    in_channels: 4
    num_classes: 3
    num_filters: 64
    ignore_index: null
    lr: 1e-3
    patience: 100

data:
  class_path: ftw_ma.datamodule.FTWMapAfricaDataModule
  init_args:
    temporal_options: windowA
    batch_size: 32
    num_workers: 8
    num_samples: -1
    data_dir: /Users/LEstes/data/labels/cropland/
    catalog: /Users/LEstes/Dropbox/projects/ftw-mappingafrica-integration/data/toycat2.csv
    normalization_strategy: min_max
    aug_list:
      - rotation
      - hflip
      - vflip
      - rescale
      - satslidemix      
      - sharpness
      - gamma
      - brightness
      - contrast
seed_everything: 42  