trainer:
  max_epochs: 100
  log_every_n_steps: 10
  accelerator: cuda
  default_root_dir: ~/working/models/ftwbaseline-zvalue_gpb-exp4a
  devices: [0]
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_top_k: 1
        save_last: true
        filename: '{epoch}-{val_loss:.2f}'
model:
  class_path: ftw_ma.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.05, 0.2, 0.75]
    loss: ce
    model: unet
    backbone: efficientnet-b3
    weights: true
    patch_weights: false
    in_channels: 4
    num_classes: 3
    ignore_index: 3
    lr: 1e-3
    patience: 100
data:
  class_path: ftw_ma.datamodule.FTWMapAfricaDataModule
  init_args:
    temporal_options: windowB
    batch_size: 32
    num_workers: 8
    num_samples: -1
    data_dir: /home/airg/data/labels/cropland/
    catalog: ~/projects/ftw-mappingafrica-integration/data/ftw-catalog2.csv
    normalization_strategy: z_value
    normalization_stat_procedure: gpb
    global_stats:
      mean: [874.538, 876.9152, 641.7087, 2925.554]
      std: [759.7574, 648.3951, 619.3338, 1083.3489]
    img_clip_val: 0
    aug_list: [rotation, hflip, vflip, sharpness]
seed_everything: 7
