trainer:
  max_epochs: 100
  log_every_n_steps: 10
  accelerator: cuda
  default_root_dir: ~/models/ftwbaseline-minmax_lab-exp3
  devices:
    - 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 0
        save_last: true
        filename: '{epoch}-{val_loss:.2f}'
model:
  class_path: ftw_ma.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights:
      - 0.04
      - 0.08
      - 0.88
    loss: ce
    model: unet
    backbone: efficientnet-b3
    weights: true
    patch_weights: false
    in_channels: 4
    num_classes: 3
    num_filters: 64
    ignore_index: 3
    lr: 1e-3
    patience: 100
data:
  class_path: ftw_ma.datamodule.FTWMapAfricaDataModule
  init_args:
    temporal_options: windowB
    batch_size: 32
    num_workers: 8
    num_samples: -1
    data_dir: /home/airg/data/labels/cropland/
    catalog: /home/airg/lestes/projects/ftw-mappingafrica-integration/data/ftw-catalog.csv
    normalization_strategy: min_max
    normalization_stat_procedure: lab
    global_stats: null
    img_clip_val: 0
    aug_list:
      - rotation
      - hflip
      - vflip
      - sharpness
seed_everything: 7
